name: publish-ofertas-from-artifact

on:
  workflow_run:
    workflows: ["Puxar arquivos do Drive"]
    types: [completed]
  workflow_dispatch: {}

permissions:
  actions: read          # <-- ESSENCIAL pra listar/baixar artifacts de outras runs
  contents: read
  pages: write
  id-token: write

jobs:
  fetch-and-publish:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Quando for disparado automaticamente por workflow_run,
      # baixa o artifact daquela execução:
      - name: Download artifact (triggered run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          name: converted-files
          path: download
          if_no_artifact_found: fail

      # Quando rodar manualmente, pega o último sucesso do workflow:
      - name: Download latest successful artifact (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "Puxar arquivos do Drive"
          workflow_conclusion: success
          branch: main
          name: converted-files
          path: download
          if_no_artifact_found: fail

      - name: Prepare site
        run: |
          set -e
          mkdir -p site
          PARQ=$(find download -type f -name 'OFERTAS.parquet' -o -name '*.parquet' | head -n1 || true)
          if [ -z "$PARQ" ]; then
            echo "Nenhum .parquet encontrado no artifact"; exit 1
          fi
          cp "$PARQ" site/OFERTAS.parquet

      - name: Upload to Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: fetch-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
