name: publish-ofertas-from-artifact

on:
  workflow_run:
    workflows: ["Puxar arquivos do Drive"]   # nome amigável do SEU workflow (ok aqui)
    types: [completed]
  workflow_dispatch: {}

permissions:
  actions: read         # <-- ESSENCIAL pra listar/baixar artifacts
  contents: read
  pages: write
  id-token: write

jobs:
  fetch-and-publish:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # quando disparado automaticamente pelo workflow_run:
      - name: Download artifact (triggered run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          name: converted-files              # <- nome do artifact do seu upload (out/**)
          path: download
          if_no_artifact_found: fail

      # quando rodar MANUALMENTE: use o NOME DO ARQUIVO .yml do workflow gerador
      - name: Download latest successful artifact (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ".github/workflows/puxar-drive.yml"   # <- ESTE filename
          workflow_conclusion: success
          branch: main
          name: converted-files
          path: download
          if_no_artifact_found: fail

      - name: Prepare site
        run: |
          set -e
          mkdir -p site
          # pega OFERTAS.parquet (ou o 1º .parquet) do artifact (direto ou de dentro de .zip)
          PARQ=$(find download -type f -name 'OFERTAS.parquet' -o -name '*.parquet' | head -n1 || true)
          if [ -z "$PARQ" ]; then
            echo "Nenhum .parquet encontrado no artifact"; exit 1
          fi
          cp "$PARQ" site/OFERTAS.parquet

      - name: Upload to Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: fetch-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
