name: publish-ofertas-from-zip

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find latest ZIP and extract OFERTAS.parquet
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y unzip
          mkdir -p site extracted
          # AJUSTE este glob se souber a pasta (ex.: pull/**/*.zip). Aqui pega o .zip mais recente do repo:
          ZIP_FILE=$(ls -1t **/*.zip | head -n1 || true)
          if [ -z "$ZIP_FILE" ]; then
            echo "Nenhum .zip encontrado no repositório"; exit 1
          fi
          echo "ZIP encontrado: $ZIP_FILE"
          unzip -o "$ZIP_FILE" -d extracted
          PARQ=$(find extracted -type f -name "OFERTAS.parquet" -o -name "*.parquet" | head -n1)
          if [ -z "$PARQ" ]; then
            echo "OFERTAS.parquet não encontrado dentro do zip"; exit 1
          fi
          cp "$PARQ" site/OFERTAS.parquet

      - name: Upload to Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
