name: Puxar arquivos do Drive

on:
  schedule:
    - cron: "*/10 * * * *"    # a cada 10 minutos (UTC)
  workflow_dispatch:          # permite rodar manualmente

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Escrever credencial da Service Account
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}
        run: |
          echo "$GDRIVE_SA_JSON" > sa.json

      - name: Baixar do Drive (limitado)
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          MAX_FILES: "50"      # pega no máx. 50 arquivos
          SINCE_HOURS: "72"    # dos últimos 3 dias
        run: |
          python scripts/drive_pull.py

      - name: Converter PDFs com meu script (gera Parquet/XLSX)
        run: |
          mkdir -p out
          python scripts/pdf27.py --once

      - name: Publicar originais como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drive-inbox
          path: inbox/**
          if-no-files-found: warn

      - name: Publicar convertidos como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-files
          path: out/**
          if-no-files-found: warn
